--INSERT INTO `vuelos`
--(`vuelosId`, `aerolinea`, `numeroVuelo`, `ciudadOrigen`, `ciudadDestino`, `partida`, `arribo`, `precio`, `conexion`)
--VALUES
--    (1,"Avianca","Av180","Argentina","Brasil","10:00", "12:00","400,00", "si");